services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql-for-minimalapi
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minimal_api
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/bitnami/mysql

volumes:
  mysql-data:
    driver: local

networks:
  default:
    name: minimalapi-net
    driver: bridge
